name: Main

on:
  push:
    branches: '**'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Grab And Throw"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "120460"
      FOMOD_REQUIRED_INSTALLATION_DIR: "Skyrim/Data"
      PUBLISH_ARCHIVE_TYPE: '7z'
      VCPKG_COMMIT_ID: '01f602195983451bc83e72f4214af2cbc495aa94'
